// Category and display name for each icon, keyed by lowercase icon id (file name without -Dark/-Light/.svg).
// scripts/build-icons.ts fails when an icon has no category, so new icons must be added here.

export const categories = {
  language: {
    c: 1, cpp: 1, cs: 1, clojure: 1, coffeescript: 1, crystal: 1, dart: 1, elixir: 1, forth: 1, fortran: 1,
    gherkin: 1, golang: 1, haskell: 1, haxe: 1, java: 1, javascript: 1, julia: 1, kotlin: 1, lua: 1, nim: 1,
    nix: 1, ocaml: 1, perl: 1, php: 1, pkl: 1, python: 1, r: 1, regex: 1, ruby: 1, rust: 1, scala: 1,
    solidity: 1, aiscript: 1, swift: 1, typescript: 1, v: 1, vala: 1, verilog: 1, zig: 1, bash: 1, powershell: 1,
    html: 1, css: 1, sass: 1, less: 1, pug: 1, markdown: 1, latex: 1, svg: 1, webassembly: 1, graphql: 1,
    matlab: 1, octave: 1, gleam: 1, json: 1, sql: 1, yaml: 1, mojo: 1,
  },
  frontend: {
    alpinejs: 1, angular: 1, astro: 1, bootstrap: 1, d3: 1, ember: 1, emotion: 1, gatsby: 1, htmx: 1, jquery: 1,
    lit: 1, materialui: 1, nextjs: 1, nuxtjs: 1, p5js: 1, pinia: 1, radixui: 1, react: 1, reactivex: 1, redux: 1,
    remix: 1, shadcnui: 1, solidjs: 1, starlight: 1, styledcomponents: 1, svelte: 1, tailwindcss: 1, tanstack: 1,
    threejs: 1, vuejs: 1, vuetify: 1, windicss: 1, yew: 1, docusaurus: 1, zod: 1, daisyui: 1, expo: 1, reactnative: 1, reactquery: 1, zustand: 1,
  },
  backend: {
    actix: 1, adonis: 1, django: 1, elysia: 1, expressjs: 1, fastapi: 1, fastify: 1, flask: 1, hibernate: 1,
    hono: 1, ktor: 1, laravel: 1, nestjs: 1, nodejs: 1, rails: 1, spring: 1, symfony: 1, trpc: 1, deno: 1, bun: 1,
    dotnet: 1, sequelize: 1, prisma: 1, drizzle: 1, mcp: 1, apollo: 1, appwrite: 1, convex: 1, gin: 1, strapi: 1, fiber: 1,
  },
  database: {
    cassandra: 1, clickhouse: 1, dynamodb: 1, elasticsearch: 1, mongodb: 1, mysql: 1, neon: 1, planetscale: 1,
    pocketbase: 1, postgresql: 1, redis: 1, sqlite: 1, sqlserver: 1, supabase: 1, turso: 1, firebase: 1, duckdb: 1, mariadb: 1, neo4j: 1, upstash: 1,
  },
  cloud: {
    aws: 1, azure: 1, cloudflare: 1, coolify: 1, gcp: 1, heroku: 1, netlify: 1, openshift: 1, openstack: 1,
    vercel: 1, workers: 1, replit: 1, webflow: 1, wordpress: 1, digitalocean: 1, fly: 1, railway: 1,
  },
  devops: {
    ansible: 1, docker: 1, git: 1, github: 1, githubactions: 1, gitlab: 1, bitbucket: 1, jenkins: 1,
    kubernetes: 1, nginx: 1, terraform: 1, rabbitmq: 1, kafka: 1, ipfs: 1, helm: 1, traefik: 1, argocd: 1,
  },
  tooling: {
    babel: 1, biome: 1, cmake: 1, eslint: 1, gradle: 1, gulp: 1, knip: 1, maven: 1, npm: 1, nx: 1, pnpm: 1,
    prettier: 1, rollupjs: 1, turborepo: 1, vite: 1, webpack: 1, yarn: 1, storybook: 1, tauri: 1, electron: 1,
    postman: 1, stackoverflow: 1, devto: 1, codepen: 1, azul: 1, esbuild: 1, rspack: 1, swc: 1, turbopack: 1, husky: 1, oxlint: 1,
  },
  testing: { cypress: 1, jest: 1, playwright: 1, selenium: 1, vitest: 1, mocha: 1, puppeteer: 1, pytest: 1, testinglibrary: 1 },
  observability: { datadog: 1, grafana: 1, langfuse: 1, opentelemetry: 1, prometheus: 1, sentry: 1, signoz: 1, posthog: 1 },
  auth: { betterauth: 1, clerk: 1, auth0: 1, authjs: 1, keycloak: 1 },
  ide: {
    androidstudio: 1, atom: 1, clion: 1, cursor: 1, eclipse: 1, emacs: 1, idea: 1, neovim: 1, phpstorm: 1,
    pycharm: 1, rider: 1, sublime: 1, vim: 1, visualstudio: 1, vscode: 1, vscodium: 1, webstorm: 1, zed: 1,
    antigravity: 1, windsurf: 1, datagrip: 1, goland: 1, helix: 1, trae: 1, warp: 1, xcode: 1,
  },
  ai: {
    chatgpt: 1, claude: 1, cline: 1, codex: 1, gemini: 1, githubcopilot: 1, ollama: 1, openclaw: 1,
    opencode: 1, opencv: 1, anaconda: 1, pytorch: 1, scikitlearn: 1, tensorflow: 1, deepseek: 1, grok: 1, huggingface: 1, jupyter: 1, langchain: 1, numpy: 1, openai: 1, pandas: 1, perplexity: 1,
  },
  design: {
    aftereffects: 1, audition: 1, blender: 1, figma: 1, illustrator: 1, photoshop: 1, premiere: 1, sketchup: 1,
    xd: 1, autocad: 1, canva: 1, inkscape: 1, sketch: 1,
  },
  game: {
    bevy: 1, gamemakerstudio: 1, godot: 1, haxeflixel: 1, processing: 1, robloxstudio: 1, unity: 1,
    unrealengine: 1, defold: 1,
  },
  payments: {
    abacatepay: 1, adyen: 1, applepay: 1, googlepay: 1, lemonsqueezy: 1, mastercard: 1, mercadopago: 1,
    paddle: 1, pagseguro: 1, paypal: 1, pix: 1, polar: 1, razorpay: 1, square: 1, stripe: 1, visa: 1, nubank: 1,
  },
  os: {
    apple: 1, arch: 1, bsd: 1, debian: 1, kali: 1, linux: 1, mint: 1, plan9: 1, raspberrypi: 1, redhat: 1,
    ubuntu: 1, windows: 1, arduino: 1, ros: 1, gtk: 1, qt: 1, flutter: 1, android: 1, ios: 1, macos: 1,
  },
  social: {
    discord: 1, discordbots: 1, discordjs: 1, fediverse: 1, activitypub: 1, gmail: 1, instagram: 1, linkedin: 1,
    mastodon: 1, misskey: 1, spotify: 1, twitter: 1, bluesky: 1, reddit: 1, slack: 1, telegram: 1, whatsapp: 1, youtube: 1,
  },
  productivity: { ableton: 1, notion: 1, obsidian: 1, n8n: 1, plane: 1, resend: 1, rocket: 1, jira: 1, linear: 1 },
} as const satisfies Record<string, Record<string, 1>>;

// Official spelling of each brand, when it differs from the file name (spaces, casing, dots...).
// Icons whose file name already matches the official spelling are not listed.
export const displayNames: Record<string, string> = {
  adonis: 'AdonisJS',
  aftereffects: 'After Effects',
  alpinejs: 'Alpine.js',
  androidstudio: 'Android Studio',
  applepay: 'Apple Pay',
  arch: 'Arch Linux',
  argocd: 'Argo CD',
  authjs: 'Auth.js',
  betterauth: 'Better Auth',
  bitbucket: 'Bitbucket',
  cpp: 'C++',
  cs: 'C#',
  daisyui: 'daisyUI',
  deno: 'Deno',
  devto: 'DEV',
  discordbots: 'Discord Bots',
  discordjs: 'discord.js',
  dotnet: '.NET',
  ember: 'Ember.js',
  expressjs: 'Express',
  fly: 'Fly.io',
  gamemakerstudio: 'GameMaker Studio',
  gcp: 'Google Cloud',
  github: 'GitHub',
  githubactions: 'GitHub Actions',
  githubcopilot: 'GitHub Copilot',
  golang: 'Go',
  googlepay: 'Google Pay',
  htmx: 'htmx',
  huggingface: 'Hugging Face',
  idea: 'IntelliJ IDEA',
  jquery: 'jQuery',
  kali: 'Kali Linux',
  lemonsqueezy: 'Lemon Squeezy',
  macos: 'macOS',
  materialui: 'Material UI',
  matlab: 'MATLAB',
  mercadopago: 'Mercado Pago',
  mint: 'Linux Mint',
  neovim: 'Neovim',
  nextjs: 'Next.js',
  nginx: 'NGINX',
  nodejs: 'Node.js',
  npm: 'npm',
  nuxtjs: 'Nuxt',
  p5js: 'p5.js',
  pandas: 'pandas',
  plan9: 'Plan 9',
  pnpm: 'pnpm',
  powershell: 'PowerShell',
  premiere: 'Premiere Pro',
  pytest: 'pytest',
  qt: 'Qt',
  radixui: 'Radix UI',
  rails: 'Ruby on Rails',
  raspberrypi: 'Raspberry Pi',
  reactnative: 'React Native',
  reactquery: 'TanStack Query',
  redhat: 'Red Hat',
  robloxstudio: 'Roblox Studio',
  rollupjs: 'Rollup',
  scikitlearn: 'scikit-learn',
  shadcnui: 'shadcn/ui',
  sketchup: 'SketchUp',
  sqlserver: 'SQL Server',
  stackoverflow: 'Stack Overflow',
  styledcomponents: 'styled-components',
  sublime: 'Sublime Text',
  tailwindcss: 'Tailwind CSS',
  testinglibrary: 'Testing Library',
  threejs: 'three.js',
  unrealengine: 'Unreal Engine',
  vim: 'Vim',
  visualstudio: 'Visual Studio',
  vscode: 'Visual Studio Code',
  vuejs: 'Vue.js',
  webpack: 'webpack',
  windicss: 'Windi CSS',
  wordpress: 'WordPress',
  workers: 'Cloudflare Workers',
  xd: 'Adobe XD',
};

export type IconCategory = keyof typeof categories;

/** Maps every icon id to its category. */
export const categoryById: Record<string, IconCategory> = Object.fromEntries(
  Object.entries(categories).flatMap(([category, ids]) =>
    Object.keys(ids).map(id => [id, category as IconCategory]),
  ),
);
