// Generates the icon data used by the Worker, the site and the package from ./icons.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { categoryById, displayNames } from '../shared/icon-categories';
import {
  API_URL,
  DEFAULT_PER_LINE,
  DEFAULT_THEME,
  MAX_PER_LINE,
  MIN_PER_LINE,
  SITE_URL,
  shortNames,
} from '../shared/icons';

process.chdir(fileURLToPath(new URL('..', import.meta.url)));

const ICONS_DIR = './icons';
const GENERATED_DIR = './generated';
const PUBLIC_SVG_DIR = './public/svg';
const PACKAGE_GENERATED_DIR = './packages/skill-icons/src/generated';

rmSync(PUBLIC_SVG_DIR, { recursive: true, force: true });
rmSync(PACKAGE_GENERATED_DIR, { recursive: true, force: true });
mkdirSync(GENERATED_DIR, { recursive: true });
mkdirSync(PUBLIC_SVG_DIR, { recursive: true });
mkdirSync(`${PACKAGE_GENERATED_DIR}/icons`, { recursive: true });

const icons: Record<string, string> = {};
for (const file of readdirSync(ICONS_DIR)
  .filter(f => f.endsWith('.svg'))
  .sort()) {
  const name = file.replace('.svg', '').toLowerCase();
  const svg = readFileSync(`${ICONS_DIR}/${file}`, 'utf8');
  icons[name] = svg;
  // Individual files let the site show thumbnails without invoking the Worker.
  writeFileSync(`${PUBLIC_SVG_DIR}/${name}.svg`, svg);
  // One module per SVG, so the package can load each icon as its own chunk.
  writeFileSync(
    `${PACKAGE_GENERATED_DIR}/icons/${name}.ts`,
    `export default ${JSON.stringify(svg.trim())};\n`,
  );
}

// Full SVG map, bundled into the Worker.
writeFileSync(`${GENERATED_DIR}/icons.json`, JSON.stringify(icons));

// Lightweight metadata, bundled into the site.
const themed = new Set(
  Object.keys(icons)
    .filter(i => i.endsWith('-light') || i.endsWith('-dark'))
    .map(i => i.split('-')[0]),
);
const names = [...new Set(Object.keys(icons).map(i => i.split('-')[0]))].sort();
const displayNameById = new Map<string, string>();
for (const file of readdirSync(ICONS_DIR).filter(f => f.endsWith('.svg')).sort()) {
  const base = file.replace(/\.svg$/, '').replace(/-(Dark|Light)$/, '');
  const id = base.toLowerCase();
  if (!displayNameById.has(id)) displayNameById.set(id, displayNames[id] ?? base);
}
const unknownDisplayNames = Object.keys(displayNames).filter(id => !displayNameById.has(id));
if (unknownDisplayNames.length) throw new Error(`Unknown icons in displayNames: ${unknownDisplayNames.join(', ')}`);
const missing = names.filter(id => !categoryById[id]);
if (missing.length) throw new Error(`Add a category in shared/icon-categories.ts for: ${missing.join(', ')}`);
const meta = names.map(name => ({ name, displayName: displayNameById.get(name)!, themed: themed.has(name), category: categoryById[name] }));
writeFileSync(`${GENERATED_DIR}/icon-list.json`, JSON.stringify(meta));

// Public catalog served at /icons.json: one entry per icon, with its display name and category.
const catalog = names.map(id => ({ id, name: displayNameById.get(id)!, category: categoryById[id] }));
writeFileSync('./public/icons.json', `${JSON.stringify(catalog, null, 2)}\n`);

// Package catalog: names, aliases and defaults mirrored from shared/icons.ts.
const banner = '// Generated by scripts/build-icons.ts. Do not edit.\n';
const list = (items: string[]) => items.map(i => `  ${JSON.stringify(i)},`).join('\n');
writeFileSync(
  `${PACKAGE_GENERATED_DIR}/catalog.ts`,
  `${banner}
export const iconNames = [
${list(names)}
] as const;

export const themedIconNames: ReadonlySet<string> = new Set([
${list([...themed].sort())}
]);

export const shortNames = ${JSON.stringify(shortNames, null, 2)} as const;

export const SITE_URL = ${JSON.stringify(SITE_URL)};
export const API_URL = ${JSON.stringify(API_URL)};
export const DEFAULT_THEME = ${JSON.stringify(DEFAULT_THEME)};
export const DEFAULT_PER_LINE = ${DEFAULT_PER_LINE};
export const MIN_PER_LINE = ${MIN_PER_LINE};
export const MAX_PER_LINE = ${MAX_PER_LINE};
`,
);

// Static import() calls, so every bundler can split one chunk per SVG.
writeFileSync(
  `${PACKAGE_GENERATED_DIR}/loaders.ts`,
  `${banner}
export const loaders: Record<string, () => Promise<{ default: string }>> = {
${Object.keys(icons)
  .map(key => `  ${JSON.stringify(key)}: () => import('./icons/${key}.js'),`)
  .join('\n')}
};
`,
);

console.log(`Generated ${names.length} icons (${Object.keys(icons).length} SVGs).`);
